title: TIL
description: 개발 공부 내용을 정리하는 개인 기술 블로그
theme: minima
markdown: kramdown

lang: ko-KR
timezone: Asia/Seoul

github_username: astar-dew

header_pages:
  - index.md
  - web/README.md
  - app/README.md
  - ai/README.md
  - cs/README.md
  - devops/README.md
  - language/README.md
  - projects/README.md
  - interview/README.md
